version : '3.8'
services:

  backend:
    container_name: backend
    env_file:
      - backend/.env
    tty: true
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: backend_database
    depends_on:
      - mongo_db
    extra_hosts:
      - "api.backend.docker:127.0.0.1"
    volumes:
      - ./backend:/app/backend
    build:
      context: backend/
      dockerfile: Dockerfile
    links:
      - mongo_db
    ports:
      - 3000:3000
    networks:
      - project-network

  frontend:
    container_name: frontend
    restart: unless-stopped
    env_file:
      - frontend/.env
    tty: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend/
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    networks:
      - project-network

  mongo_db:
    tty: true
    container_name: mongo_db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=backend_database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    build:
      context: database/
      dockerfile: Dockerfile
    volumes:
      - ./database:/app/database
      - ./mongodatabase:/data/db
    ports:
      - 27017:27017
    networks:
      - project-network

  import-database:
    build:
      context: database/import_database
      dockerfile: Dockerfile
    volumes:
      - ./database:/app/database
    networks:
      - project-network
    depends_on:
      - mongo_db

networks:
  project-network:
    driver: bridge